name: 'CybeDefend Action'
description: 'Run security scans with CybeDefend directly in your GitHub Actions workflows'
author: 'CybeDefend'
inputs:
  api-key:
    description: 'API Key for CybeDefend'
    required: true
  project-id:
    description: 'Project ID for the scan'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'blue'
