name: 'CybeDefend Action'
description: 'Run security scans with CybeDefend directly in your GitHub Actions workflows'
author: 'CybeDefend'
inputs:
  api_key:
    description: 'API Key of the CybeDefend account'
    required: true
  project_id:
    description: 'Project ID for the scan'
    required: true
  wait:
    description: 'Wait for scan completion'
    required: false
    default: 'true'
  interval:
    description: 'Interval in seconds between status checks when waiting for scan completion'
    required: false
    default: '5'
  break_on_fail:
    description: 'Exit with error code if scan fails'
    required: false
    default: 'false'
  break_on_severity:
    description: 'Exit with error code if vulnerabilities of specified severity or above are detected (critical, high, medium, low, none)'
    required: false
    default: ''
  region:
    description: 'Region to use for API endpoints (us, eu). Sets CYBEDEFEND_REGION and is ignored if api_url is provided.'
    required: false
    default: ''
  api_url:
    description: 'Custom API base URL. Takes precedence over region and environment variables.'
    required: false
    default: ''
  branch:
    description: 'Branch name to associate with the scan (e.g., main, develop, feature/my-feature)'
    required: true
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'blue'
