name: Update Major Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Any version like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  update-major-tag:
    name: Update Major Tag to Latest vX.x.x
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move major tag to latest commit
        run: |
          echo "🔵 Extracting major version..."
          TAG_REF="${GITHUB_REF##*/}" # Example: v2.3.1
          MAJOR_VERSION=$(echo "$TAG_REF" | sed -E 's/^(v[0-9]+)\..*/\1/')
          
          echo "✅ Moving $MAJOR_VERSION to current commit..."
          
          git fetch --tags
          git tag -d "$MAJOR_VERSION" || true
          git tag "$MAJOR_VERSION"
          git push origin "$MAJOR_VERSION" --force
